[package]
name = "ferrisfetch"
version = "0.3.0"
edition = "2021"

[dependencies]
sysinfo = "0.30"
whoami = "1.5"

x11rb = {version = "0.13.1", features = ["randr"]}

ash = "0.38"
nvml-wrapper = "0.10"
rocm_smi_lib = "0.2"